<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>async4</title>
</head>
<script>
	async function c (){
		return 'hello';
	}
	c().then(v =>console.log(v));
	//hello
	async function d(){
		throw new Error('error');
	}
	d().then(
			v=>console.log(v) 
		).catch(e=>console.log(e))
	

</script>
<body>
	<strong>返回 Promise 对象
async函数返回一个 Promise 对象。</strong>
<br>
<pre>
	async函数内部抛出错误，会导致返回的 Promise 对象变为reject状态。抛出的错误对象会被catch方法回调函数接收到。
</pre>
</body>
</html>